version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db:postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}"
    networks:
      - app_network
    command: ["/wait-for-it.sh", "db:5432", "--", "npm", "start"]

  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5433:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./sql/01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql"
      - "./sql/02_seedData.sql:/docker-entrypoint-initdb.d/02_seedData.sql"
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network: